### ISSUE TITLE
Known static return value from react-redux hook

### ISSUE THREAD

**Issue by Glinkis** [yuchi/hooks.macro#13]
I'm pretty sure the `useDispatch` hook in the `react-redux` package returns a referentially equal value every time, so it should be safe to omit it from the dependency arrays.

[Here](https://github.com/reduxjs/react-redux/blob/master/src/hooks/useDispatch.js) is the source for this hook.

**Comment by yuchi** [comment]
Thank you for your suggestion! I was thinking about that just yesterday and if you dig deeper you’ll discover that `dispatch` is essentially `useContext(…).store.dispatch`. Contexts are not inherently static, you can literally change the store at runtime in this specific case, and adding them to the “known static values” would produce extremely obscure bugs.

Let me close the issue as wontfix for these reasons, and reopen it if you think I got something wrong.
