### ISSUE TITLE
Support React 17?

### ISSUE THREAD

**Issue by vitexikora** [yuchi/hooks.macro#27]
Peer dependencies mention only React 16.8. 
This makes it impossible to install in Node 16+ without legacy-peer-deps flag.. 😢

**Comment by adrianhelvik** [comment]
The react version in devDependencies should be changed to `>=16.8.0 <=18.*.*`. React supports the hooks this macro uses in all those versions.

@yuchi

**Comment by vitexikora** [comment]
Can you please merge it @yuchi ?

**Comment by yuchi** [comment]
Should have been fixed in v1.2.0.
Sorry for the delay and for not having merged your PR.
PS: In future contributions do NOT upgrade the version please

**Comment by vitexikora** [comment]
Thanks! Finally can get rid off `legacy-peer-deps`...
