### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by sfsekaran** [yuchi/hooks.macro#9]
This should be fairly easy.

The type of `useAutoCallback(T)` should just be T.

The type of `useAutoMemo((...args: any): S)` should be S.

**Comment by yuchi** [comment]
Hi @sfsekaran, in theory I already put typings in the project. They are referenced [here in the _package.json_][0] and defined [here in _hooks.macro.d.ts_][1].

Can you please tell me what issues are you having? Care to share a snippet of your own code?

[0]: https://github.com/yuchi/hooks.macro/blob/bbc3947e758af03316e4edd4f34942241ff10554/package.json#L8
[1]: https://github.com/yuchi/hooks.macro/blob/bbc3947e758af03316e4edd4f34942241ff10554/src/hooks.macro.d.ts

**Comment by yuchi** [comment]
Let me close the issue, since TypeScript is already supported.

Feel free to re-open if you think I missed something.
